export const categorySections = [
  {
    label: "Best Seller",
    slug: "best-seller",
    description: "Pilihan terlaris pelanggan hari ini.",
  },
  {
    label: "Makanan Berat",
    slug: "makanan-berat",
    description: "Menu utama untuk makan siang atau makan malam.",
  },
  {
    label: "Makanan Ringan",
    slug: "makanan-ringan",
    description: "Camilan dan side dish untuk teman nongkrong.",
  },
  {
    label: "Minuman",
    slug: "minuman",
    description: "Minuman segar dan hangat untuk melengkapi pesanan.",
  },
  {
    label: "Paket Hemat",
    slug: "paket-hemat",
    description: "Combo hemat yang cocok untuk sekali pesan.",
  },
] as const;

export const menuItems = [
  {
    name: "Ayam Bakar Madu",
    description: "Ayam bakar juicy dengan nasi hangat, sambal matah, dan lalapan segar.",
    price: "Rp38.000",
    priceValue: 38000,
    accent: "from-[#c95a34] to-[#f0b36d]",
    categories: ["best-seller", "makanan-berat"] as const,
  },
  {
    name: "Sapi Lada Hitam",
    description: "Irisan sapi tumis lada hitam dengan paprika dan saus gurih pedas.",
    price: "Rp52.000",
    priceValue: 52000,
    accent: "from-[#2b5b53] to-[#74b29d]",
    categories: ["best-seller", "makanan-berat"] as const,
  },
  {
    name: "Nasi Goreng Kampung",
    description: "Nasi goreng gurih dengan telur mata sapi, ayam suwir, dan acar.",
    price: "Rp34.000",
    priceValue: 34000,
    accent: "from-[#7a421f] to-[#e1a25d]",
    categories: ["makanan-berat"] as const,
  },
  {
    name: "Chicken Katsu Curry",
    description: "Chicken katsu renyah dengan saus kari Jepang dan nasi pulen.",
    price: "Rp44.000",
    priceValue: 44000,
    accent: "from-[#7e5a1c] to-[#f1c36b]",
    categories: ["makanan-berat"] as const,
  },
  {
    name: "Mie Goreng Seafood",
    description: "Mie goreng wok hei dengan cumi, udang, dan sayuran segar.",
    price: "Rp42.000",
    priceValue: 42000,
    accent: "from-[#8b3d2f] to-[#db8962]",
    categories: ["makanan-berat"] as const,
  },
  {
    name: "Truffle Fries",
    description: "Kentang goreng renyah dengan parmesan dan mayonnaise truffle.",
    price: "Rp26.000",
    priceValue: 26000,
    accent: "from-[#9b6238] to-[#f1cf8b]",
    categories: ["makanan-ringan"] as const,
  },
  {
    name: "Chicken Pop Bites",
    description: "Potongan ayam crispy dengan saus smoky mayo pedas manis.",
    price: "Rp28.000",
    priceValue: 28000,
    accent: "from-[#a84d2b] to-[#f5b36f]",
    categories: ["makanan-ringan"] as const,
  },
  {
    name: "Tahu Cabe Garam",
    description: "Tahu crispy dengan taburan cabe, bawang putih, dan daun jeruk.",
    price: "Rp22.000",
    priceValue: 22000,
    accent: "from-[#6f5232] to-[#dcc08b]",
    categories: ["makanan-ringan"] as const,
  },
  {
    name: "Pisang Karamel Keju",
    description: "Pisang goreng hangat dengan saus karamel dan topping keju lembut.",
    price: "Rp24.000",
    priceValue: 24000,
    accent: "from-[#8c5f26] to-[#f0c674]",
    categories: ["makanan-ringan"] as const,
  },
  {
    name: "Garlic Bread Melt",
    description: "Roti panggang gurih dengan garlic butter dan keju mozzarella.",
    price: "Rp21.000",
    priceValue: 21000,
    accent: "from-[#6f4d2d] to-[#d9b27f]",
    categories: ["makanan-ringan"] as const,
  },
  {
    name: "Lychee Yakult Spark",
    description: "Minuman sparkling manis segar untuk teman makan siang atau malam.",
    price: "Rp18.000",
    priceValue: 18000,
    accent: "from-[#b2466e] to-[#f7b1c8]",
    categories: ["best-seller", "minuman"] as const,
  },
  {
    name: "Es Kopi Aren",
    description: "Espresso dingin dengan susu segar dan gula aren yang creamy.",
    price: "Rp20.000",
    priceValue: 20000,
    accent: "from-[#604133] to-[#c48e72]",
    categories: ["minuman"] as const,
  },
  {
    name: "Matcha Cloud Latte",
    description: "Latte matcha lembut dengan foam susu yang ringan dan creamy.",
    price: "Rp24.000",
    priceValue: 24000,
    accent: "from-[#446a42] to-[#add7a4]",
    categories: ["minuman"] as const,
  },
  {
    name: "Lemon Tea Dingin",
    description: "Teh lemon dingin yang segar dan ringan untuk semua menu.",
    price: "Rp16.000",
    priceValue: 16000,
    accent: "from-[#d6a534] to-[#f8df85]",
    categories: ["minuman"] as const,
  },
  {
    name: "Chocolate Hazelnut Shake",
    description: "Milkshake cokelat hazelnut dingin dengan rasa rich dan lembut.",
    price: "Rp27.000",
    priceValue: 27000,
    accent: "from-[#5e3b33] to-[#d09a83]",
    categories: ["minuman"] as const,
  },
  {
    name: "Paket Ayam Hemat",
    description: "Ayam bakar, nasi, sambal, dan lemon tea dalam satu paket hemat.",
    price: "Rp49.000",
    priceValue: 49000,
    accent: "from-[#9c4328] to-[#efb169]",
    categories: ["paket-hemat"] as const,
  },
  {
    name: "Paket Katsu Duo",
    description: "Chicken katsu curry dengan garlic bread dan minuman pilihan.",
    price: "Rp57.000",
    priceValue: 57000,
    accent: "from-[#7c601e] to-[#f0c56c]",
    categories: ["paket-hemat"] as const,
  },
  {
    name: "Paket Sharing Snack",
    description: "Truffle fries, chicken pop bites, dan dua pilihan saus favorit.",
    price: "Rp45.000",
    priceValue: 45000,
    accent: "from-[#84532d] to-[#e8c37b]",
    categories: ["paket-hemat"] as const,
  },
  {
    name: "Paket Lunch Beef",
    description: "Sapi lada hitam, nasi hangat, dan lemon tea untuk makan siang.",
    price: "Rp61.000",
    priceValue: 61000,
    accent: "from-[#36584a] to-[#78b1a0]",
    categories: ["paket-hemat"] as const,
  },
  {
    name: "Paket Tea Time",
    description: "Pisang karamel keju, garlic bread melt, dan matcha cloud latte.",
    price: "Rp46.000",
    priceValue: 46000,
    accent: "from-[#8d5b3a] to-[#f0c986]",
    categories: ["paket-hemat"] as const,
  },
] as const;
